# -*- coding: utf-8 -*-
"""automate_Agil Firli Gunawan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouqTgG50tYRXoDNTff3of9fcnPiT0mPJ
"""

import pandas as pd
import zipfile
import os

def preprocessing_data():

    zip_path = 'fake-and-real-news-dataset.zip'
    if not os.path.exists('Fake.csv') or not os.path.exists('True.csv'):
        if os.path.exists(zip_path):
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall('.')
            print(f"Extracted {zip_path} successfully.")
        else:
            print(f"Error: Zip file '{zip_path}' not found. Please ensure it's in the correct directory.")
            return None

    fake_df = pd.read_csv("Fake.csv")
    true_df = pd.read_csv("True.csv")

    fake_df['label'] = 'FAKE'
    true_df['label'] = 'REAL'

    df = pd.concat([fake_df, true_df], ignore_index=True)

    df = df[['title', 'text', 'label']]

    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)

    df['content'] = df['title'] + " " + df['text']

    df = df[['content', 'label']]

    df.to_csv("fake_news_clean.csv", index=False)

    print("Preprocessing selesai!")
    print("Ukuran dataset:", df.shape)

    return df


if __name__ == "__main__":
    preprocessing_data()